### ISSUE TITLE
Transmit emails to SMTP servers that requires STARTTLS or authenticated connection

### ISSUE THREAD

**Issue by ghost** [axel-angel/whatsapp-email-bridge#1]
> python WhatsAppEmailForwarder.py
> 
> ```
> Parsing config
> Starting
> Starting input thread
> Connecting
> <= WhatsApp: Logged in
> <= WhatsApp: <- XXXXXXXXXXX@s.whatsapp.net Message
> Traceback (most recent call last):
>   File "WhatsAppEmailForwarder.py", line 265, in <module>
>     stack.start()
>   File "WhatsAppEmailForwarder.py", line 185, in start
>     self.stack.loop()
>   File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 57, in loop
>   File "/usr/lib/python2.7/asyncore.py", line 216, in loop
>     poll_fun(timeout, map)
>   File "/usr/lib/python2.7/asyncore.py", line 156, in poll
>     read(obj)
>   File "/usr/lib/python2.7/asyncore.py", line 87, in read
>     obj.handle_error()
>   File "/usr/lib/python2.7/asyncore.py", line 83, in read
>     obj.handle_read_event()
>   File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
>     self.handle_read()
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 48, in handle_read
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 55, in receive
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 56, in toUpper
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 56, in toUpper
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 56, in toUpper
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 56, in toUpper
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 56, in toUpper
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 161, in receive
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 102, in receive
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 56, in toUpper
>   File "build/bdist.linux-x86_64/egg/yowsup/layers/interface/interface.py", line 38, in receive
>   File "WhatsAppEmailForwarder.py", line 77, in onMessage
>     self.onTextMessage(mEntity)
>   File "WhatsAppEmailForwarder.py", line 117, in onTextMessage
>     s.sendmail(dst, [dst], msg.as_string())
>   File "/usr/lib/python2.7/smtplib.py", line 724, in sendmail
>     raise SMTPSenderRefused(code, resp, from_addr)
> smtplib.SMTPSenderRefused: (530, '5.7.0 Must issue a STARTTLS command first. o3sm16362213pdj.5 - gsmtp', 'YYYYYYYYYYYY@gmail.com')
> ```

**Comment by axel-angel** [comment]
If I understand correctly, you are trying to send your email directly to gmail but it doesn't work because of the requirement gmail has: it requires TLS. This can probably be fixed easily by calling tentatively starttls on s, I'll give it a try.

Moreover it will probably fail because gmail is not gonna accept an email coming from a anywhere (dynamic address on the internet, no guarantee and probably spam). In my case I don't have this problem because I have a SMTP server locally configured for internet email, thus it can send email (to gmail for example). In your case you have two choice: 
 (1) Either you have a local SMTP server that deliver in a local box you can read (no code change required), or
(2) You authenticate using your google credentials to gmail (their smtp server) to send yourself an email (need some small changes: add optional auth to the smtp server login/password).

Anyway the 2 option seems a good idea to allow anyone who doesn't have a local SMTP server to profit from this program (probably many people!).

**Comment by axel-angel** [comment]
Oh by the way I recommend you censure your phone number (in the WhatsApp address) and your gmail address (in the last exception) to avoid SPAM and such not-so-nice things.

EDIT: Actually I've done it for you.

**Comment by ghost** [comment]
Thank you , Problem Resolved..:)

**Comment by axel-angel** [comment]
I have added by default a tentative to use STARTTLS, it should work for you too, can you test it? You need to update your whatsapp_config for the new options.
