### ISSUE TITLE
Emitted emails should use the sender's name in the From field

### ISSUE THREAD

**Issue by goenie** [axel-angel/whatsapp-email-bridge#9]
Can you fix this

**Comment by axel-angel** [comment]
I need more detail because I don't understand your issue.

Do you mean some information is missing in the email? Or something is not working as expected? You should explain what you have done, what was the result and what do you expect instead.

**Comment by goenie** [comment]
The problem i have is, i set reply in config: {}@emailadres.xxx
When i receive an Email from Whatsapp-email-bridge the sender is 31xxxxxxxx not 31xxxxxxxxx@emailadres.xxx
Is it clear now? 
Hope you can help me.

**Comment by axel-angel** [comment]
Yes, it's clearer. When you reply, the email address should be "31xxxxxxxxx@emailadres.xxx". Can you confirm this? The address you see is the human-friendly version (I decided to show the number instead of the address, it's like showing the name "Axel Angel" instead of the address "axel.angel@domain.com").

(Originally it was displaying the recipient name but yowsup changed and now the phone number appears which is less nice).

**Comment by goenie** [comment]
Yes i can confirm this. 
Outlook or any other mail client cannot work with a number, you cannot save it as contact.
phone number @domain.com is more workable for me.
I hope you can give me directions how to resolve this or work something out.
I love this program.

**Comment by axel-angel** [comment]
Ok, I found how to get the name. It was so unintuitive I didn't belive it until I tried*. Should be much more user-friendly (like it used to be) and it should solve your issue.

*: https://github.com/tgalal/yowsup/issues/863

**Comment by goenie** [comment]
Works like a charm, thank you

**Comment by axel-angel** [comment]
:)
